name: chotoder_chora_kobita
description: "A class Flutter project."
publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6 # State Management!
  get_it: ^8.0.2
  sqflite: ^2.4.1
  path: ^1.9.0
  intl: ^0.20.0
  image: ^4.3.0
  carousel_slider: ^5.1.1
  dart_code_linter: ^2.0.0
  equatable: ^2.0.5
  uuid: ^4.5.1
  share_plus: ^12.0.0
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/english/class/
    - assets/images/english/class_1/
    - assets/images/english/class_2/
    - assets/images/english/class_3/


  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/NotoSerifBengali-Regular.ttf
        - asset: fonts/NotoSerifBengali-Bold.ttf
        - asset: fonts/NotoSerifBengali-ExtraBold.ttf
          weight: 700