// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'chotoder_chora_kobita';
  static const String PROJECT_VERSION = '1.0.1';
  static const String NOTOSERIFBENGALI_BOLD = 'NotoSerifBengali-Bold';
  static const String NOTOSERIFBENGALI_EXTRABOLD = 'NotoSerifBengali-ExtraBold';
  static const String NOTOSERIFBENGALI_REGULAR = 'NotoSerifBengali-Regular';
}
